In [29]:
from robot_library_py import *
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Joy, JointState
from intera_core_msgs.msg import JointCommand

from threading import Thread
import time
import numpy as np 
from std_msgs.msg import Bool
import rotm2euler

from utils_camera import MyRealSense, CVCamera
import cv2
from matplotlib import pyplot as plt
import pickle
import datetime
import os 
import argparse

import argparse
import json
import numpy as np
import time
import os
import shutil
import psutil
import sys
import socket
import traceback

from collections import OrderedDict

import torch
from torch.utils.data import DataLoader

import robomimic
import robomimic.utils.train_utils as TrainUtils
import robomimic.utils.torch_utils as TorchUtils
import robomimic.utils.obs_utils as ObsUtils
import robomimic.utils.env_utils as EnvUtils
import robomimic.utils.file_utils as FileUtils
from robomimic.config import config_factory
from robomimic.algo import algo_factory, RolloutPolicy
from robomimic.utils.log_utils import PrintLogger, DataLogger, flush_warnings

import matplotlib.pyplot as plt
import h5py

import os
import time 

from utils_ros import ROSInterface
import traceback

In [2]:
dir="/home/carl/data_sawyer/models/"
fn="model_epoch_600.pth"
ckpt_path=dir+fn

ckpt_path = "/home/carl/data_sawyer/models/dclose_rnn_model_epoch_600.pth"
assert os.path.exists(ckpt_path)

In [3]:
device = TorchUtils.get_torch_device(try_to_use_cuda=True)

# restore policy
policy, ckpt_dict = FileUtils.policy_from_checkpoint(ckpt_path=ckpt_path, device=device, verbose=True)
pass 

============= Loaded Config =============
{
    "algo_name": "bc",
    "experiment": {
        "name": "sawyer_dclose",
        "validate": false,
        "logging": {
            "terminal_output_to_txt": true,
            "log_tb": true,
            "log_wandb": false,
            "wandb_proj_name": "dclose"
        },
        "save": {
            "enabled": true,
            "every_n_seconds": null,
            "every_n_epochs": 20,
            "epochs": [],
            "on_best_validation": false,
            "on_best_rollout_return": false,
            "on_best_rollout_success_rate": true
        },
        "epoch_every_n_steps": 500,
        "validation_epoch_every_n_steps": 50,
        "env": null,
        "additional_envs": null,
        "render": false,
        "render_video": true,
        "keep_all_videos": false,
        "video_skip": 5,
        "rollout": {
            "enabled": false,
            "n": 50,
            "horizon": 1000,
            "rate": 20,
            

/home/carl/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/carl/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


============= Loaded Policy =============
ObservationKeyToModalityDict: action not found, adding action to mapping with assumed low_dim modality!
BC_RNN (
  ModuleDict(
    (policy): RNNActorNetwork(
        action_dim=3
  
        encoder=ObservationGroupEncoder(
            group=obs
            ObservationEncoder(
                Key(
                    name=agentview_image
                    shape=[3, 84, 84]
                    modality=rgb
                    randomizer=CropRandomizer(input_shape=[3, 84, 84], crop_size=[76, 76], num_crops=1)
                    net=VisualCore(
                      input_shape=[3, 76, 76]
                      output_shape=[64]
                      backbone_net=ResNet18Conv(input_channel=3, input_coord_conv=False)
                      pool_net=SpatialSoftmax(num_kp=32, temperature=1.0, noise=0.0)
                    )
                    sharing_from=None
                )
                Key(
                    name=robot0_eef_pos
         

In [4]:
ckpt_dict = FileUtils.maybe_dict_from_checkpoint(ckpt_path=ckpt_path, ckpt_dict=None)
# algo name and config from model dict
algo_name, _ = FileUtils.algo_name_from_checkpoint(ckpt_dict=ckpt_dict)
config, _ = FileUtils.config_from_checkpoint(algo_name=algo_name, ckpt_dict=ckpt_dict, verbose=False)

config.unlock()
config.train.data="/home/carl/data_sawyer/block/demos.hdf5"
config.lock()

ObsUtils.initialize_obs_utils_with_config(config)
dataset_path = os.path.expanduser(config.train.data)
shape_meta = FileUtils.get_shape_metadata_from_dataset(
    dataset_path=config.train.data,
    all_obs_keys=config.all_obs_keys,
    verbose=True
)


============= Initialized Observation Utils with Obs Spec =============

using obs modality: low_dim with keys: ['robot0_eef_pos']
using obs modality: rgb with keys: ['robot0_eye_in_hand_image', 'agentview_image']
using obs modality: depth with keys: []
using obs modality: scan with keys: []
obs key agentview_image with shape (84, 84, 3)
obs key robot0_eef_pos with shape (6,)
obs key robot0_eye_in_hand_image with shape (84, 84, 3)


In [5]:
def demo2actions(hdf5_file, demo_key, rollout_policy): 
    rollout_policy.start_episode()


    demo=hdf5_file['data'][demo_key]
    actions_real=demo['actions']
    obs=demo['obs']
    N=obs['robot0_eye_in_hand_image'].shape[0]

    obss=[]
    for i in range(N):
        ob={k:obs[k][i] for k in obs.keys()} 
        ob['robot0_eye_in_hand_image']=ob['robot0_eye_in_hand_image'].transpose(2,0,1)
        ob['agentview_image']=ob['agentview_image'].transpose(2,0,1)
        obss.append(ob)

    acs=[]
    for ob in obss: 
        ob = rollout_policy._prepare_observation(ob)
        ac = rollout_policy.policy.get_action(obs_dict=ob, goal_dict=None)
        ac=ac.detach().cpu().numpy()[0]
        acs.append(ac)

    actions_pred=np.array(acs)
    return actions_real, actions_pred

In [6]:
rclpy.init()

urdf_path = os.getcwd() +'/'+'sawyer.urdf'  #'/home/carl/sawyer_robot_ros2/src/teleop_script/sawyer.urdf'
robot = URDFModel(urdf_path)
jointMap = {name: ind for ind, name in enumerate(robot.jointNames)}


joint_names=['right_j0', 'right_j1', 'right_j2', 'right_j3', 'right_j4', 'right_j5', 'right_j6']
joint_inds=[jointMap[name] for name in joint_names]


node = Node('infer_live')
q = robot.getJoints()
ros_interface = ROSInterface(node, robot)
cmd_pub = node.create_publisher(JointCommand, '/robot/limb/right/joint_command', 10)

t1 = Thread(target=ros_interface.spin_thread)
t1.start()

sawyer
link: 0
	cog: 0 0 0
	inertia: 1 1 1 0 0 0
	mass: 1
	name: base
link: 1
	cog: 0 0 0
	inertia: 1e-08 1e-08 1e-08     0     0     0
	mass: 0.0001
	name: torso
link: 2
	cog:    0    0 -0.5
	inertia:    5.06359    6.08689    4.96192 0.00105311   0.801996 0.00103417
	mass: 60.864
	name: pedestal
link: 3
	cog: 0 0 0
	inertia: 1 1 1 0 0 0
	mass: 1
	name: controller_box
link: 4
	cog: 0 0 0
	inertia: 1 1 1 0 0 0
	mass: 1
	name: pedestal_feet
link: 5
	cog:  -0.0006241 -2.8025e-05    0.065404
	inertia:   0.0067599   0.0067877   0.0074031  1.5888e-05 -6.1904e-07 -4.2024e-05
	mass: 2.0687
	name: right_arm_base_link
link: 6
	cog: 0.024366 0.010969  0.14363
	inertia:  0.053314  0.057902  0.023659 0.0080179  0.011734 0.0047093
	mass: 5.3213
	name: right_l0
link: 7
	cog:   0.0053207 -2.6549e-05      0.1021
	inertia:    0.011833   0.0082709   0.0049661  4.2124e-07  4.9425e-05 -4.4669e-06
	mass: 1.5795
	name: head
link: 8
	cog: 0 0 0
	inertia: 1e-08 1e-08 1e-08     0     0     0
	mass: 0.0001
	name

In [7]:
def get_ee(jointmsg):
    msg=jointmsg    
    q =  robot.getJoints() 
    for ind, name in enumerate(msg.name):
        if name in jointMap:
            q[jointMap[name]] = msg.position[ind]
    robot.setJoints(q)
    
    # T=robot.getBodyTransform('right_l6');
    T=robot.getBodyTransform('camera_link');
    xyz=T[0:3,3]
    e1 = rotm2euler.rotationMatrixToEulerAngles(T[0:3, 0:3])
    ee6=np.concatenate([xyz, e1])
    return ee6

def set_vels(vels):
    cmd_msg = JointCommand()
    cmd_msg.names = robot.jointNames
    cmd_msg.mode = cmd_msg.VELOCITY_MODE
    cmd_msg.header.stamp = rclpy.clock.Clock().now().to_msg()
    cmd_msg.velocity =vels 
    cmd_pub.publish(cmd_msg)

def goto_xyzrpy(target, delay=0.1, tol=0.05):
    ee6=get_ee(ros_interface.latest_joint_states)
    xd=ee6-target
    xd[3:6]=0 

    # print('xd: ', xd)

    alpha = .0001
    I = np.eye(q.shape[0])

    while np.linalg.norm(xd)>tol:
        ee6=get_ee(ros_interface.latest_joint_states)
        xd=target-ee6 
        xd[3:6]=0        # only xyz, rpy not working yet

        J = robot.getJacobian('camera_link')
        
        qd = np.linalg.inv(J.T @ J + alpha * I) @ J.T @ xd

        set_vels(list(qd))
        time.sleep(delay)
    
    # stop
    set_vels([0.0]*10)

apos=0
def goto_q_pos_velocity_ctrl(target_q, alpha=0.7, tol=0.01,  delay=0.1, maxstep=50):
    global apos
    target_jointpos=target_q
    cpos=robot.getJoints()
    dpos=np.linalg.norm(target_jointpos-cpos)

    step =0
    while dpos>tol: 
        cpos=robot.getJoints()
        dpos=np.linalg.norm(target_jointpos-cpos)
          

        qd =(target_jointpos-cpos)*alpha
        apos=qd 
        if np.max(qd) <0.001:
            print('reached')
            break 


        set_vels(list(qd))
        time.sleep(delay)
        step +=1

        if step>=maxstep:
            break 
        
    set_vels([0.0]*10)

### Robot safety check

In [10]:
pos1=robot.getJoints()
pos1

array([ 0.25362402, -0.29735156,  0.2595332 , -1.92522363,  1.4523877 ,
       -1.24452832, -1.88056152,  0.57152637,  0.041667  ,  0.        ])

In [11]:
goto_q_pos_velocity_ctrl(pos1, tol=0.11)

### set robot to initial pos

In [12]:
block_start_pos = np.array([ 0.25362402, -0.1616416 ,  0.2595332 , -1.92522363,  1.4523877 ,
       -1.24452832, -1.8799541 ,  0.57152539,  0.03735149,  0.        ])

In [15]:
goto_q_pos_velocity_ctrl(block_start_pos, tol=0.15)

### dclose

In [8]:
ee_init_pos_dclose=np.array([ 0.57437793, -0.67592773,  0.6533125 , -2.36299512,  1.27580859,
       -1.42587598, -1.64586621,  2.84970117,  0.        ,  0.        ])

In [9]:
goto_q_pos_velocity_ctrl(ee_init_pos_dclose, tol=0.05)

### Trajectory playing test

In [33]:
dataset_path = "/home/carl/data_sawyer/dclose/demos_10d.hdf5"


f = h5py.File(dataset_path, "r")
demos = list(f["data"].keys())
len(demos)

53

In [35]:
demo_name="demo_52"
demo=f['data'][demo_name]
actions=demo['actions']
ee_pos=demo['obs']['robot0_eef_pos']
ee_pos.shape

(50, 6)

In [61]:
goto_xyzrpy(ee_pos[0], tol=0.005) 

In [37]:
for i in range(len(ee_pos)):
    goto_xyzrpy(ee_pos[i], delay=0.001, tol=0.02) 

goto_xyzrpy(ee_pos[i], tol=0.005)  # last one with precision

In [60]:
goto_xyzrpy(ee_pos[-1], tol=0.005)

In [43]:
eepos_current=ee_pos[0]
eepos_current

array([ 0.55606356,  0.18831051,  0.3377421 , -0.0208837 ,  0.75747543,
       -1.54219383])

### Robot is ready

In [11]:
policy.start_episode()

In [12]:
def get_current_obs():
    # img_wrist=cam_wrist.get_current_frame(scale=0.5)  
    # img_front=cam_front.get_current_frame(scale=0.5) 

    image_wrist=ros_interface.image_wrist
    image_front=ros_interface.image_front

    if image_front.sum()==0.0:
        print('image front None')
        return None
    if image_wrist.sum()==0:
        print('image wrist None')
        return None 

    scale=0.5
    img_wrist = cv2.resize(image_wrist, (int(image_wrist.shape[1]*scale), int(image_wrist.shape[0]*scale) ) , interpolation = cv2.INTER_AREA)
    img_front = cv2.resize(image_front, (int(image_front.shape[1]*scale), int(image_front.shape[0]*scale) ) , interpolation = cv2.INTER_AREA)


    # print('shape: ', image_wrist.shape, image_front.shape)
    msg=ros_interface.latest_joint_states
    gripper_isopen=ros_interface.latest_gripper_state

    ee=get_ee(msg)

    try:
        pos =np.array([msg.position[ind] for ind in joint_inds])
        vel =np.array([msg.velocity[ind] for ind in joint_inds])
        t=msg.header.stamp.sec+msg.header.stamp.nanosec*1e-9
    except Exception as e:
        # print('msg=', msg)
        # print('Error=',e, e.st)
        # traceback.print_exc()
        return None 

    img_wrist=cv2.cvtColor(img_wrist, cv2.COLOR_BGR2RGB)
    img_front=cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB)

    img_wrist=cv2.resize(img_wrist, (84,84))
    img_front=cv2.resize(img_front, (84,84))


    ob={'agentview_image': img_front, 'robot0_eye_in_hand_image': img_wrist, 'robot0_joint_pos': pos, 'robot0_joint_vel':vel, 'robot0_eef_pos': ee}
    ob['robot0_eye_in_hand_image']=ob['robot0_eye_in_hand_image'].transpose(2,0,1)
    ob['agentview_image']=ob['agentview_image'].transpose(2,0,1)

    return ob

In [13]:
ob=get_current_obs()
ob!=None 

True

In [15]:
ob.keys()

dict_keys(['agentview_image', 'robot0_eye_in_hand_image', 'robot0_joint_pos', 'robot0_joint_vel', 'robot0_eef_pos'])

In [ ]:
# ob=get_current_obs()
# ob = policy._prepare_observation(ob)
# ac = policy.policy.get_action(obs_dict=ob, goal_dict=None)
# ac=ac.detach().cpu().numpy()[0]
# ac 

In [ ]:
# ob=get_current_obs()
# ob = policy._prepare_observation(ob)
# ac = policy.policy.get_action(obs_dict=ob, goal_dict=None)
# ac=ac.detach().cpu().numpy()[0]
# ac 

In [59]:
goto_xyzrpy(ee_pos[0], tol=0.005) 

In [56]:
eepos_start=ee_pos[0]
eepos_current=eepos_start
eepos_current

array([ 0.55606356,  0.18831051,  0.3377421 , -0.0208837 ,  0.75747543,
       -1.54219383])

In [57]:
frequency = 20.0   # similar to robomimic

st=time.time()
for i in range(1000000):
    ob=get_current_obs()
    if ob==None:
        continue

    ob2 = policy._prepare_observation(ob)
    ac = policy.policy.get_action(obs_dict=ob2, goal_dict=None)
    ac=ac.detach().cpu().numpy()[0]
    print(f'i={i} ac={ac}')

    eepos_current[:3] += ac 
    print(f'eepos_togo: {eepos_current}')

    goto_xyzrpy(eepos_current, tol=0.01)
    


    image_front=ob['agentview_image'].transpose(2,1,0) 
    image_wrist=ob['robot0_eye_in_hand_image'].transpose(2,1,0)
    

    image=np.concatenate([image_wrist, image_front], axis=1) 
    image= cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    cv2.imshow('frame',image)
    if cv2.waitKey(1) == 27: 
        print('UI closed')
        break  # esc to quit

    time.sleep(1.0/frequency)

cv2.destroyAllWindows() 

i=0 ac=[-0.00318676 -0.00739707  0.00128674]
eepos_togo: [ 0.5528768   0.18091345  0.33902884 -0.0208837   0.75747543 -1.54219383]
i=1 ac=[-0.00348016 -0.00818213  0.0013851 ]
eepos_togo: [ 0.54939664  0.17273132  0.34041395 -0.0208837   0.75747543 -1.54219383]
i=2 ac=[-0.00289517 -0.00764384  0.00120982]
eepos_togo: [ 0.54650147  0.16508749  0.34162377 -0.0208837   0.75747543 -1.54219383]
i=3 ac=[-0.0028277  -0.00778312  0.00120305]
eepos_togo: [ 0.54367377  0.15730436  0.34282683 -0.0208837   0.75747543 -1.54219383]
i=4 ac=[-0.00285662 -0.00789622  0.00138684]
eepos_togo: [ 0.54081716  0.14940815  0.34421367 -0.0208837   0.75747543 -1.54219383]
i=5 ac=[-0.00100982 -0.00263081  0.00041437]
eepos_togo: [ 0.53980734  0.14677734  0.34462804 -0.0208837   0.75747543 -1.54219383]
i=6 ac=[-0.00177788 -0.00366927  0.00077921]
eepos_togo: [ 0.53802946  0.14310806  0.34540725 -0.0208837   0.75747543 -1.54219383]
i=7 ac=[-0.00203358 -0.00475525  0.0008562 ]
eepos_togo: [ 0.53599589  0.13835282  

KeyboardInterrupt: 

### success: worked for the first time: (note: doesn't stop)

In [51]:
# eepos_current[:3] += ac 
# eepos_current

array([ 0.54482866,  0.15848914,  0.34229148, -0.0208837 ,  0.75747543,
       -1.54219383])

In [ ]:
goto_xyzrpy(ee_pos[0], tol=0.005) 

In [62]:
cv2.destroyAllWindows() 